name: Run eslint on changed files
description: Run ESLint on JavaScript files
author: jackton1
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT'
    required: true
    default: ${{ github.token }}
  config_path:
    description: Eslint configuration path
    required: false
    default: '.eslintrc'
  ignore_path:
    description: Eslint ignore path
    required: false
    default: ''
  extensions:
    description: Comma separated list of extensions
    required: false
    default: 'ts,tsx,js,jsx'
  extra_args:
    description: Eslint extra arguments
    required: false
    default: ''
  exclude_path:
    description: String or list of files to exclude entirely
    required: false
    default: ''
  working-directory:
    description: Working directory or project root
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding: 
  icon: check-square
  color: white
